CREATE TABLE crs_record
(
  id BIGSERIAL PRIMARY KEY NOT NULL,
  gwf_ref     VARCHAR(254) NOT NULL,
  vaf_no      VARCHAR(100) NOT NULL,
  cas_no      VARCHAR(100),
  cos_no      VARCHAR(100),
  post_name   VARCHAR(100) NOT NULL,
  family_name VARCHAR(254),
  other_name  VARCHAR(254),
  gender      VARCHAR(10),
  date_of_birth   TIMESTAMP NOT NULL,
  nationality  VARCHAR(10) NOT NULL,
  passport_no  VARCHAR(20) NOT NULL,
  mobile_no  VARCHAR(20),
  email_address  VARCHAR(254),
  local_address  VARCHAR(500),
  status  VARCHAR(20),
  ec_type  VARCHAR(10),
  entry_type  VARCHAR(10),
  visa_endorsement  VARCHAR(100),
  valid_from   TIMESTAMP NOT NULL,
  valid_to   TIMESTAMP NOT NULL,
  sponsor_name    VARCHAR(250),
  sponsor_type    VARCHAR(250),
  sponsor_address    VARCHAR(250),
  sponsor_spx_no VARCHAR(100),
  add_endors_1 VARCHAR(100),
  add_endors_2 VARCHAR(100),
  cat_d_endors_1 VARCHAR(1000),
  cat_d_endors_2 VARCHAR(1000),
  uni_college_name VARCHAR(500),
  brp_collection_info VARCHAR(500),
  expected_travel_date  TIMESTAMP,
  updated   TIMESTAMP DEFAULT NOW()
);