ALTER TABLE visa_type ADD COLUMN description VARCHAR(200);
UPDATE visa_type set description = 'General student visa - Part time course (Tier 4)' where name = 'Tier 4 (General) Student' and notes = 'Part time course';
UPDATE visa_type set description = 'General student visa  - Privately funded (Tier 4)' where name = 'Tier 4 (General) Student' and notes = 'Privately funded';
UPDATE visa_type set description = 'General student visa - Studying full-time at degree level and above at a Higher Education Institute (Tier 4)' where name = 'Tier 4 (General) Student' and notes='Studying full-time at degree level and above at a HEI';
UPDATE visa_type set description = 'General student visa - Studying full-time on a course below degree level at a Higher Education Institute (Tier 4)' where name = 'Tier 4 (General) Student' and notes = 'Studying full-time on a course below degree level at a HEI';
UPDATE visa_type set description = 'General student visa - Further Education - any NQF Level (Tier 4)' where name = 'Tier 4 (General) Student' and notes = 'Further Education - any NQF Level';
UPDATE visa_type set description = 'Sponsored General student visa  - Privately funded (Tier 4)' where name = 'Tier 4 (General (S)) Student' and notes = 'Privately funded';
UPDATE visa_type set description = 'Sponsored General student visa - Studying full-time at degree level and above at a Higher Education Institute (Tier 4)' where name = 'Tier 4 (General (S)) Student' and notes = 'Studying full-time at degree level and above at a HEI';
UPDATE visa_type set description = 'Sponsored General student visa - Studying full-time on a course below degree level at a Higher Education Institute (Tier 4)' where name = 'Tier 4 (General (S)) Student' and notes = 'Studying full-time on a course below degree level at a HEI';
UPDATE visa_type set description = 'Sponsored General student visa - Further Education - any NQF Level (Tier 4)' where name = 'Tier 4 (General (S)) Student' and notes = 'Further Education - any NQF Level';
UPDATE visa_type set description = 'General student''s dependant partner visa - 9 months and over study at degree level (Tier 4)' where name = 'Tier 4 (General) Dependent Partner' and notes = '9+ Months Study  Degree level';
UPDATE visa_type set description = 'General student''s dependant partner visa - under 9 months study (Tier 4)' where name = 'Tier 4 (General) Dependent Partner' and notes = '9- Months Study';
UPDATE visa_type set description = 'General student''s dependant partner visa - studying a course below degree level (Tier 4)' where name = 'Tier 4 (General) Dependent Partner' and notes = 'Studying a course below degree level';
UPDATE visa_type set description = 'General student''s dependant child visa - 9 months and over study at degree level (Tier 4)' where name = 'Tier 4 (General) Dependent Child' and notes = 'Studying more than 9 Months at Degreel level and above';
UPDATE visa_type set description = 'General student''s dependant child visa - under 9 months study (Tier 4)' where name = 'Tier 4 (General) Dependent Child' and notes = 'Studying less than 9 Months';
UPDATE visa_type set description = 'General student''s dependant child visa - studying a course below degree level (Tier 4)' where name = 'Tier 4 (General) Dependent Child' and notes = 'Studying less than 9 Months or below degree level';
UPDATE visa_type set description = 'Child (16 and over) sponsored student visa (Tier 4)' where name = 'Tier 4 (Child(S)) Student' and notes = '<16 yrs old';
UPDATE visa_type set description = 'Child (under 16) sponsored student visa (Tier 4)' where name = 'Tier 4 (Child(S)) Student' and notes = '16+ yrs old';
UPDATE visa_type set description = 'Child (16 and over) student visa (Tier 4)' where name = 'Tier 4 (Child) Student' and notes = '16+';
UPDATE visa_type set description = 'Child (under 16) student visa (Tier 4)' where name = 'Tier 4 (Child) Student' and notes = '16-';
UPDATE visa_type set description = 'Youth Mobility Scheme visa (Tier 5)' where name = 'TIER 5 (YOUTH MOB) MIGRANT';
UPDATE visa_type set description = 'Temporary Worker - Charity Worker visa (Tier 5)' where name = 'TIER 5 TW (CHARITY) MIGRANT';
UPDATE visa_type set description = 'Temporary Worker - Creative and Sporting visa (Tier 5)' where name = 'TIER 5 TW (CRE-SPORT) MIGRANT';
UPDATE visa_type set description = 'Temporary Worker - Government Authorised Exchange visa (Tier 5)' where name = 'TIER 5 TW (EXCHANGE) MIGRANT';
UPDATE visa_type set description = 'Temporary Worker - International Agreement visa (Tier 5)' where name = 'TIER 5 TW (INT AGREE) MIGRANT';
UPDATE visa_type set description = 'Temporary Worker - Religious Worker visa (Tier 5)' where name = 'TIER 5 TW (RELIGIOUS) MIGRANT';
UPDATE visa_type set description = 'Temporary Worker''s Partner visa (Tier 5)' where name = 'TIER 5 TW PARTNER';
UPDATE visa_type set description = 'Temporary Worker''s dependant child visa (Tier 5)' where name = 'TIER 5 TW CHILD';
UPDATE visa_type set description = 'General work visa (Tier 2)' where name = 'Tier 2 (General) Migrant';
UPDATE visa_type set description = 'Graduate Trainee Intra-company Transfer visa (Tier 2)' where name = 'Tier 2 (ICT) Graduate Trainee';
UPDATE visa_type set description = 'Minister of Religion visa (Tier 2)' where name = 'Tier 2 (Min of Rel) Migrant';
UPDATE visa_type set description = 'Sportsperson visa (Tier 2)' where name = 'Tier 2 (Sportspeople) Migrant';
UPDATE visa_type set description = 'General work visa (Tier 2) for a partner' where name = 'Tier 2 Partner';
UPDATE visa_type set description = 'General work visa (Tier 2) for a dependant child' where name = 'Tier 2 Child';
UPDATE visa_type set description = 'Intra-company Transfer visa (Tier 2)' where name = 'Tier 2 ICT Long Term Staff Migrant';
UPDATE visa_type set description = 'Intra-company Transfer visa (Tier 2) for a partner' where name = 'Tier 2 ICT Long Term Staff Partner';
UPDATE visa_type set description = 'Intra-company Transfer visa (Tier 2) for a dependant child' where name = 'Tier 2 ICT Long Term Staff Child';

